In [2]:
import numpy as np

P0 = np.matrix([[.75, .05, .1, .1],
               [ 0.1 ,0.4 ,0.3, 0.2],
               [0.05, 0.4, 0.4, 0.15],
               [0.1, 0.35, 0.1, 0.45]])

P1 = np.matrix([[0.5, 0.2, 0.2, 0.1],
               [0.05, 0.6, 0.15, 0.2],
               [0, 0.3, 0.6, 0.1],
               [0, 0.6, 0.1, 0.3]])

IM0 = np.matrix([[0.8, 0.1, 0.1, 0.0],
                [0.1, 0.7, 0.1, 0.1],
                [0.0, 0.1, 0.4, 0.5],
                [0.0, 0.5, 0.1, 0.4]])

IM1 = np.matrix([[0.1, 0.6, 0.3, 0.0],
                [0.7, 0.2, 0.1, 0.0],
                [0.1, 0.1, 0.1, 0.7],
                [0.2, 0.2, 0.2, 0.4]])

print P0
print
print P1
print
print IM0
print
print IM1

[[ 0.75  0.05  0.1   0.1 ]
 [ 0.1   0.4   0.3   0.2 ]
 [ 0.05  0.4   0.4   0.15]
 [ 0.1   0.35  0.1   0.45]]

[[ 0.5   0.2   0.2   0.1 ]
 [ 0.05  0.6   0.15  0.2 ]
 [ 0.    0.3   0.6   0.1 ]
 [ 0.    0.6   0.1   0.3 ]]

[[ 0.8  0.1  0.1  0. ]
 [ 0.1  0.7  0.1  0.1]
 [ 0.   0.1  0.4  0.5]
 [ 0.   0.5  0.1  0.4]]

[[ 0.1  0.6  0.3  0. ]
 [ 0.7  0.2  0.1  0. ]
 [ 0.1  0.1  0.1  0.7]
 [ 0.2  0.2  0.2  0.4]]


In [3]:
#reversed v_1 * M_1to M_1 * v_1

vm =  IM1[0:,0] * IM0[0,0:] + IM1[0:,1] * IM0[1,0:] + IM1[0:,2] * IM0[2,0:] +IM1[0:,3] * IM0[3,0:]
vm

matrix([[ 0.14,  0.46,  0.19,  0.21],
        [ 0.58,  0.22,  0.13,  0.07],
        [ 0.09,  0.44,  0.13,  0.34],
        [ 0.18,  0.38,  0.16,  0.28]])

In [4]:
s = .4
c0_to_c1 = ((1-s) * P0)+ (s * vm)
c0_to_c1

matrix([[ 0.506,  0.214,  0.136,  0.144],
        [ 0.292,  0.328,  0.232,  0.148],
        [ 0.066,  0.416,  0.292,  0.226],
        [ 0.132,  0.362,  0.124,  0.382]])

In [5]:
import random

def normalize(arr):
    s = sum(arr)

    if s == 0:
        s = 1
        arr[0] = 1
    
    for i, val in enumerate(arr):
        arr[i] = val/s


def generate(width, height):
    matrix = []

    for i in range(height):
        matrix.append([])

        for j in range(width):
            matrix[i].append(float(random.randint(0, 1000))/1000)

        normalize(matrix[i])

        matrix[i] = [round(x, 3) for x in matrix[i]]
        
    return np.matrix(matrix)

generate(4,4)


matrix([[ 0.351,  0.131,  0.13 ,  0.388],
        [ 0.073,  0.231,  0.452,  0.244],
        [ 0.757,  0.074,  0.124,  0.045],
        [ 0.028,  0.467,  0.425,  0.08 ]])

In [6]:
def initialize(soc0, soc1):
    matricies = []
    
    for i in range(4):
        matricies.append(generate(4,4))
    #format is as follows [P0, IM0, P1, IM1]

    P0, IM0, P1, IM1 = matricies

    vm1 =  IM1[0:,0] * IM0[0,0:] + IM1[0:,1] * IM0[1,0:] + IM1[0:,2] * IM0[2,0:] +IM1[0:,3] * IM0[3,0:]
    vm2 =  IM0[0:,0] * IM1[0,0:] + IM0[0:,1] * IM1[1,0:] + IM0[0:,2] * IM1[2,0:] +IM0[0:,3] * IM1[3,0:]
    c0_to_c1 = ((1-soc0) * P0)+ (soc0 * vm1)
    c1_to_c0 = ((1-soc1) * P1)+ (soc1 * vm2)
    
    matricies.append(c0_to_c1)
    matricies.append(c1_to_c0)
    
    if random.randint(0,1) == 1:
        position_and_direction = ['right', 'left', 'left', 'right']
    else:
        position_and_direction = ['left', 'right', 'right', 'left']
    
    return matricies#, position_and_direction
    
initialize(.3,.4)
    
    
    

[matrix([[ 0.011,  0.694,  0.262,  0.033],
         [ 0.406,  0.303,  0.198,  0.092],
         [ 0.474,  0.089,  0.063,  0.373],
         [ 0.147,  0.346,  0.197,  0.31 ]]),
 matrix([[ 0.142,  0.193,  0.255,  0.41 ],
         [ 0.284,  0.335,  0.154,  0.227],
         [ 0.323,  0.082,  0.435,  0.161],
         [ 0.266,  0.142,  0.288,  0.304]]),
 matrix([[ 0.317,  0.358,  0.035,  0.289],
         [ 0.028,  0.354,  0.172,  0.446],
         [ 0.136,  0.186,  0.232,  0.446],
         [ 0.419,  0.242,  0.311,  0.028]]),
 matrix([[ 0.02 ,  0.172,  0.308,  0.5  ],
         [ 0.051,  0.395,  0.393,  0.161],
         [ 0.586,  0.197,  0.044,  0.174],
         [ 0.194,  0.324,  0.158,  0.324]]),
 matrix([[ 0.0929516,  0.5331208,  0.2762704,  0.0977496],
         [ 0.3709561,  0.2712768,  0.2259474,  0.1312376],
         [ 0.3916968,  0.1245227,  0.118806 ,  0.3645877],
         [ 0.1799346,  0.3036838,  0.2163224,  0.3001066]]),
 matrix([[ 0.2868612,  0.3282936,  0.099234 ,  0.2851132],
       

In [14]:
def traverse(matrix):
    rand  = float(random.randint(0,1000))/1000
    count = 0
    for i, elem in enumerate(matrix):
        if rand > count and rand < count + elem:
            return i
        count += elem
    return len(matrix) - 1


def continue_chain(emo1, emo2, matricies):
    T1, T2 = matricies
    
    if random.randint(0,1) == 1:
        position_and_direction = ['right', 'left', 'left', 'right']
    else:
        position_and_direction = ['left', 'right', 'right', 'left']

    return (traverse(T1.A[emo1]), traverse(T2.A[emo2]))#, position_and_direction 

continue_chain(0,0,initialize(.3,.4)[4:])

(1, 0)